project:
  type: website
  output-dir: docs
  resources:
  - fonts/*.*
  - img/*.*

execute:
  freeze: auto

website:
  title: "ROeS 2027"
  cookie-consent:
    type: express
    style: headline
    policy-url: https://www.roes2027.org/imprint-and-privacy-policy.html
    prefs-text: "Cookie Preferences & Privacy Policy"
  navbar:
    left:
      - text: "About"
        menu: 
        - text: "Overview"
          href: index.qmd
        - text: "Committees"
          href: committees.qmd
        - text: "Imprint"
          href: imprint-and-privacy-policy.qmd
      - text: "Key Dates"
        href: key-dates.qmd

format:
  html:
    theme: 
    - zephyr-black.scss
    - custom.scss
    css: styles.css
    toc: true

